package org.jss.polytechnic.dao;

public interface Queries {

	String INSERT_STAGING_EXAM_RESULTS = "INSERT INTO STAGING_EXAM_RESULTS(SL_NO, REG_NO,STUDENT_NAME,SEMESTER,EX1,EX2,EX3,EX4,EX5,EX6,EX7,EX8,EX9,EX_TOTAL,IA1,IA2,IA3,IA4,IA5,IA6,IA7,IA8,IA9,IA_TOTAL,TOTAL,RESULT,QP1,QP2,QP3,QP4,QP5,QP6,QP7,QP8,QP9,STATUS) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

	String UPDATE_STAGING_EXAM_STATUS = "UPDATE STAGING_EXAM_RESULTS SET STATUS = 1";

	String INSERT_EXAM_RESULTS = "INSERT INTO EXAM_RESULTS SELECT REG_NO,STUDENT_NAME,SEMESTER,EX1,EX2,EX3,EX4,EX5,EX6,EX7,EX8,EX9,EX_TOTAL,IA1,IA2,IA3,IA4,IA5,IA6,IA7,IA8,IA9,IA_TOTAL,TOTAL,RESULT,QP1,QP2,QP3,QP4,QP5,QP6,QP7,QP8,QP9 FROM STAGING_EXAM_RESULTS SER "
			+ "WHERE NOT EXISTS (SELECT NULL FROM EXAM_RESULTS ER WHERE ER.REG_NO = SER.REG_NO AND ER.SEMESTER = SER.SEMESTER) AND STATUS = 0";

	String GET_RESULTS_TO_BE_UPDATED = "SELECT STUDENT_NAME, RESULT,REG_NO,SEMESTER,EX1,EX2,EX3,EX4,EX5,EX6,EX7,EX8,EX9,IA1,IA2,IA3,IA4,IA5,IA6,IA7,IA8,IA9,QP1,QP2,QP3,QP4,QP5,QP6,QP7,QP8,QP9  FROM STAGING_EXAM_RESULTS SER "
			+ "WHERE EXISTS (SELECT NULL FROM EXAM_RESULTS ER WHERE ER.REG_NO = SER.REG_NO AND ER.SEMESTER =SER.SEMESTER) AND STATUS = 0";

	String UPDATE_EXAM_RESULTS = "UPDATE EXAM_RESULTS SET EX_TOTAL = ?, IA_TOTAL = ?, TOTAL = ?, RESULT = ? WHERE REG_NO = ? AND SEMESTER = ?";

	String UPDATE_EXAM_MARKS = "UPDATE EXAM_RESULTS SET EX1=COALESCE(?,EX1),EX2=COALESCE(?,EX2),EX3=COALESCE(?,EX3)"
			+ ",EX4=COALESCE(?,EX4),EX5=COALESCE(?,EX5),EX6=COALESCE(?,EX6),EX7=COALESCE(?,EX7),EX8=COALESCE(?,EX8),EX9=COALESCE(?,EX9)"
			+ ",IA1=COALESCE(?,IA1),IA2=COALESCE(?,IA2),IA3=COALESCE(?,IA3)"
			+ ",IA4=COALESCE(?,IA4),IA5=COALESCE(?,IA5),IA6=COALESCE(?,IA6),IA7=COALESCE(?,IA7),IA8=COALESCE(?,IA8),IA9=COALESCE(?,IA9)"
			+ " WHERE REG_NO = ? AND SEMESTER = ?";

	String UPDATE_EXAM_TOTAL = "update exam_results "
			+ "set ex_total = IF(ex1 = 'AB',0,ex1) + IF(ex2 = 'AB',0,ex2) + IF(ex3 = 'AB',0,ex3) + IF(ex4 = 'AB',0,ex4) + IF(ex5 = 'AB',0,ex5) + IF(ex6 = 'AB',0,ex6) + IF(ex7 = 'AB',0,ex7) + IF(ex8 = 'AB',0,ex8) + IF(ex9 = 'AB',0,ex9),"
			+ "ia_total = IF(ia1 = 'AB',0,ia1) + IF(ia2 = 'AB',0,ia2) + IF(ia3 = 'AB',0,ia3) + IF(ia4 = 'AB',0,ia4) + IF(ia5 = 'AB',0,ia5) + IF(ia6 = 'AB',0,ia6) + IF(ia7 = 'AB',0,ia7) + IF(ia8 = 'AB',0,ia8) + IF(ia9 = 'AB',0,ia9),"
			+ "total = ex_total+ia_total";

	String UPDATE_FAIL_EXAM_RESULT = "UPDATE EXAM_RESULTS SET RESULT = ? "
			+ "WHERE (EX1 < ? OR NULLIF(EX1,'') IS NULL) "
			+ "AND (EX2 < ? OR NULLIF(EX2,'') IS NULL) "
			+ "AND (EX3 < ? OR NULLIF(EX3,'') IS NULL) "
			+ "AND (EX4 < ? OR NULLIF(EX4,'') IS NULL) "
			+ "AND (EX5 < ? OR NULLIF(EX5,'') IS NULL) "
			+ "AND (EX6 < ? OR NULLIF(EX6,'') IS NULL) "
			+ "AND (EX7 < ? OR NULLIF(EX7,'') IS NULL) "
			+ "AND (EX8 < ? OR NULLIF(EX8,'') IS NULL) "
			+ "AND (EX9 < ? OR NULLIF(EX9,'') IS NULL) "
			+ "AND (IA1 < ? OR NULLIF(IA1,'') IS NULL) "
			+ "AND (IA2 < ? OR NULLIF(IA2,'') IS NULL) "
			+ "AND (IA3 < ? OR NULLIF(IA3,'') IS NULL) "
			+ "AND (IA4 < ? OR NULLIF(IA4,'') IS NULL) "
			+ "AND (IA5 < ? OR NULLIF(IA5,'') IS NULL) "
			+ "AND (IA6 < ? OR NULLIF(IA6,'') IS NULL) "
			+ "AND (IA7 < ? OR NULLIF(IA7,'') IS NULL) "
			+ "AND (IA8 < ? OR NULLIF(IA8,'') IS NULL) "
			+ "AND (IA9 < ? OR NULLIF(IA9,'') IS NULL) ";

	String UPDATE_PASS_EXAM_RESULT = "UPDATE EXAM_RESULTS SET RESULT = ? WHERE RESULT != ?";

	String INSERT_STUDENT_INFO = "INSERT INTO STUDENT_INFO(REG_NO, NAME,FATHER,MOTHER,GENDER,CATEGORY) VALUES (?,?,?,?,?,?)";

}
