CREATE TABLE IF NOT EXISTS USER_INFO
(USERNAME VARCHAR(16) PRIMARY KEY, PASSWORD VARCHAR(32) NOT NULL, ROLE INT(2)); 


INSERT INTO USER_INFO VALUES ('RAMA',MD5('RAMA'),1);
COMMIT;

SELECT * FROM USER_INFO;

