CREATE TABLE IF NOT EXISTS USER_INFO
(USERNAME VARCHAR(16) PRIMARY KEY, PASSWORD VARCHAR(32) NOT NULL, ROLE INT(2)); 

DROP TABLE IF EXISTS STUDENT_INFO;

CREATE TABLE IF NOT EXISTS STUDENT_INFO
(REG_NO VARCHAR(50) ,NAME VARCHAR(100),FATHER VARCHAR(100),MOTHER VARCHAR(100),GENDER VARCHAR(1),CATEGORY VARCHAR(10),BRANCH VARCHAR(25), PRIMARY KEY (REG_NO));

CREATE TABLE IF NOT EXISTS STAGING_EXAM_RESULTS
(SL_NO VARCHAR(4),REG_NO VARCHAR(50), STUDENT_NAME VARCHAR(50),SEMESTER VARCHAR(2), EX1 VARCHAR(3),EX2 VARCHAR(3),EX3 VARCHAR(3),EX4 VARCHAR(3),EX5 VARCHAR(3),EX6 VARCHAR(3),EX7 VARCHAR(3),EX8 VARCHAR(3),EX9 VARCHAR(3),EX_TOTAL VARCHAR(4),IA1 VARCHAR(3),IA2 VARCHAR(3),IA3 VARCHAR(3),IA4 VARCHAR(3),IA5 VARCHAR(3),IA6 VARCHAR(3),IA7 VARCHAR(3),IA8 VARCHAR(3),IA9 VARCHAR(3),IA_TOTAL VARCHAR(3),TOTAL VARCHAR(4),RESULT VARCHAR(25), QP1 VARCHAR(10),QP2 VARCHAR(10),QP3 VARCHAR(10),QP4 VARCHAR(10),QP5 VARCHAR(10),QP6 VARCHAR(10),QP7 VARCHAR(10),QP8 VARCHAR(10),QP9 VARCHAR(10), STATUS INT(1));

CREATE TABLE IF NOT EXISTS EXAM_RESULTS
(REG_NO VARCHAR(50), STUDENT_NAME VARCHAR(50),SEMESTER VARCHAR(2), EX1 VARCHAR(3),EX2 VARCHAR(3),EX3 VARCHAR(3),EX4 VARCHAR(3),EX5 VARCHAR(3),EX6 VARCHAR(3),EX7 VARCHAR(3),EX8 VARCHAR(3),EX9 VARCHAR(3),EX_TOTAL VARCHAR(4),IA1 VARCHAR(3),IA2 VARCHAR(3),IA3 VARCHAR(3),IA4 VARCHAR(3),IA5 VARCHAR(3),IA6 VARCHAR(3),IA7 VARCHAR(3),IA8 VARCHAR(3),IA9 VARCHAR(3),IA_TOTAL VARCHAR(3),TOTAL VARCHAR(4),RESULT VARCHAR(25), QP1 VARCHAR(10),QP2 VARCHAR(10),QP3 VARCHAR(10),QP4 VARCHAR(10),QP5 VARCHAR(10),QP6 VARCHAR(10),QP7 VARCHAR(10),QP8 VARCHAR(10),QP9 VARCHAR(10));

CREATE TABLE IF NOT EXISTS SUBJECT (BRANCH VARCHAR(50), ACADEMIC_YEAR VARCHAR(10), SEMESTER INT(10),SUBJECT_CODE VARCHAR(10), SUBJECT_NAME VARCHAR(50));

INSERT INTO USER_INFO VALUES ('RAMA',MD5('RAMA'),1);
COMMIT;

SELECT * FROM STAGING_EXAM_RESULTS;

SELECT * FROM EXAM_RESULTS;

select count(*) from exam_results;
select count(*) from STAGING_EXAM_RESULTS;

DELETE FROM STAGING_EXAM_RESULTS;
DELETE FROM EXAM_RESULTS;

DROP TABLE EXAM_RESULTS;

DROP TABLE STAGING_EXAM_RESULTS;

INSERT INTO EXAM_RESULTS SELECT REG_NO,STUDENT_NAME,SEMESTER,EX1,EX2,EX3,EX4,EX5,EX6,EX7,EX8,EX9,EX_TOTAL,IA1,IA2,IA3,IA4,IA5,IA6,IA7,IA8,IA9,IA_TOTAL,TOTAL,RESULT,QP1,QP2,QP3,QP4,QP5,QP6,QP7,QP8,QP9 FROM STAGING_EXAM_RESULTS SER
			WHERE NOT EXISTS (SELECT NULL FROM EXAM_RESULTS ER WHERE ER.REG_NO = SER.REG_NO AND ER.SEMESTER =SER.SEMESTER);

SELECT REG_NO,SEMESTER,EX1,EX2,EX3,EX4,EX5,EX6,EX7,EX8,EX9,IA1,IA2,IA3,IA4,IA5,IA6,IA7,IA8,IA9
FROM STAGING_EXAM_RESULTS SER
WHERE EXISTS (SELECT NULL FROM EXAM_RESULTS ER WHERE ER.REG_NO = SER.REG_NO AND ER.SEMESTER =SER.SEMESTER);

select * from exam_results where reg_no = '314ME10060' and semester = '2';

update exam_results set ex1='',ex3=ex3 where reg_no = '314ME10060' and semester = '2';